# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='embedding',
            new_name='scenario',
        ),
        migrations.AddField(
            model_name='option',
            name='unrooted',
            field=models.BooleanField(default=False),
        ),
    ]
