# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0002_auto_20160309_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='option',
            name='label',
            field=models.TextField(max_length=100),
        ),
    ]
