# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0003_auto_20160904_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='step',
            field=models.FloatField(default=1),
        ),
    ]
